### ISSUE TITLE
How to use extra/vqa/parse.py?

### ISSUE THREAD

**Issue by jcjohnson** [jacobandreas/nmn2#11]
I'm trying to get this code running on a new dataset and I can't figure out the expected input format of extra/vqa/parse.py. It looks like it is trying to parse the output of the Stanford Dependency parser, but I'm having a hard time getting nontrivial parses.

I have an input file containing one question per line, including the example question from the README:

``` bash
> cat questions.txt
Is the train modern?
What color is the man's swimsuit?
```

I can parse these questions using the Stanford Dependency parser, (throwing away stderr for clarity):

```
> ./lexparser.sh questions.txt 2> /dev/null
(ROOT
  (SQ (VBZ Is)
    (NP (DT the) (NN train))
    (ADJP (JJ modern))
    (. ?)))

cop(modern-4, Is-1)
det(train-3, the-2)
nsubj(modern-4, train-3)
root(ROOT-0, modern-4)

(ROOT
  (SBARQ
    (WHNP (WDT What) (NN color))
    (SQ (VBZ is)
      (NP
        (NP (DT the) (NN man) (POS 's))
        (NN swimsuit)))
    (. ?)))

det(color-2, What-1)
dobj(is-3, color-2)
root(ROOT-0, is-3)
det(man-5, the-4)
nmod:poss(swimsuit-7, man-5)
case(man-5, 's-6)
nsubj(is-3, swimsuit-7)
```

This looks vaguely like the expected input format that parse.py is trying to parse, but I only get trivial parses when piping this directly to parse.py:

```
> ./lexparser.sh questions.txt 2> /dev/null | python extra/vqa/parse.py
(_what _thing)
(_what _thing)
(_what _thing)
```

Am I doing something blatantly wrong? Even if you don't have functioning code for this I'd really appreciate any insight on how to use parse.py.

**Comment by jacobandreas** [comment]
Run with these flags:

```
java -mx150m -cp "$scriptdir/*:" edu.stanford.nlp.parser.lexparser.LexicalizedParser \
 -outputFormat "words,typedDependencies" -outputFormatOptions "stem,collapsedDependencies,includeTags" \
 -sentences newline \
 edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz \
 $*
```

(sorry, this is apparently not documented anywhere)

**Comment by jacobandreas** [comment]
Updated parse.py docs per 82e9a9980d39c771d2f780d9d400478fd83e9422

**Comment by jcjohnson** [comment]
Thanks for the quick response! That is working perfectly.
