### ISSUE TITLE
Unknown precedence for type advmod

### ISSUE THREAD

**Issue by kushalkafle** [jacobandreas/nmn2#12]
The presence of `advmod` in the input throws an error because there is no entry for it in the code to determine precedence for it.

**Comment by jacobandreas** [comment]
Sorry about the slow reply. You should be fine giving it the same precedence as nmod in the `precedence` function.

**Comment by kushalkafle** [comment]
Thanks for confirming that. I did a bit of looking around into the advmod and thought the same. Its a good sigh of relief that I choose the right thing though !
