### ISSUE TITLE
how to generates the content of vqa/conv  ?

### ISSUE THREAD

**Issue by SeekPoint** [jacobandreas/nmn2#14]
--is this a script?
 while conv contains the result of preprocessing these images with a 16-layer VGGNet as described in the paper. Every file in the conv directory should be of the form COCO_{SETNAME}_{IMAGEID}.jpg.npz, and contain a 512x14x14 image map in zipped numpy format.

**Comment by jacobandreas** [comment]
https://gist.github.com/jacobandreas/897987ac03f8d4b9ea4b9e44affa00e7

**Comment by MattX** [comment]
Hey! Any pointers as to where I can find the pretrained model you use (`lrcn_finetune_vgg_trainval_iter_100000.caffemodel`)? I've been looking around but have had no luck.
Thanks!

**Comment by jacobandreas** [comment]
This is a VGGNet that's been attached to an LRCN (
http://jeffdonahue.com/lrcn/) and fine-tuned for COCO captions. Not sure if
there's a public model you can download, but you should be able to rebuild
it yourself using the code at that site. Or just use the standard VGG
instead.
