### ISSUE TITLE
Any way to save the model?

### ISSUE THREAD

**Issue by jamesclyeh** [jacobandreas/nmn2#16]
I tried saving it using SnapshotLogger, but when I tried to load it back in the constructor of NMN, it gave me an error saying that I am "loading into empty net". 
I figured this is because the layers of the network is not yet defined in the constructor. 
But because the layout of the network is dynamic, I am not exactly sure if the current saving/loading mechanism will work. Do you have any suggestions?

**Comment by ShangxuanWu** [comment]
Same question here.

**Comment by jacobandreas** [comment]
Add this line to the training script:

    model.apollo_net.save("model.caffemodel")
