### ISSUE TITLE
Inner product size error in image preprocessing by gist code

### ISSUE THREAD

**Issue by xhzhao** [jacobandreas/nmn2#17]
hi all
When i run the gist code[https://gist.github.com/jacobandreas/897987ac03f8d4b9ea4b9e44affa00e7], i got an error: F0220 13:52:50.173866 14142 inner_product_layer.cpp:61] Check failed: K_ == new_K (25088 vs. 100352) Input size incompatible with inner product parameters.

It seems that there is a size mismatch in the inner product. According to the paper, the image features are computed by the fifth convolutional layers , so i think the inner product should be removed from the prototxt[https://gist.githubusercontent.com/ksimonyan/211839e770f7b538e2d8/raw/0067c9b32f60362c74f4c445a080beed06b07eb3/VGG_ILSVRC_16_layers_deploy.prototxt]
I removed all the ops after "fc6", and the error is gone.

But i'm not sure whether it's right or wrong?

**Comment by jacobandreas** [comment]
Yes, that's right. I can upload a copy of my modified prototxt, but sounds
like you've already got it working.
