### ISSUE TITLE
Issues to run the code

### ISSUE THREAD

**Issue by jwyang** [jacobandreas/nmn2#2]
Hi, Jacob,

Much thanks for releasing the code. 

Recently, I tried to run the code. After installing apollocaffe, I implemented run.sh, then got the following errors:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import models
  File "/home/jwyang/Researches/nmn2/models/**init**.py", line 3, in <module>
    import apollocaffe
  File "/home/jwyang/Researches/apollocaffe/python/apollocaffe/**init**.py", line 1, in <module>
    from cpp._apollocaffe import Tensor, ApolloNet, CppConfig, make_numpy_data_param, Blob
  File "/home/jwyang/Researches/apollocaffe/python/apollocaffe/cpp/__init__.py", line 1, in <module>
    import _apollocaffe
ImportError: No module named _apollocaffe

It is said no module apollocaffe is found. Do you have any idea about this error? 

thanks,
jianwei

**Comment by jacobandreas** [comment]
Have you configured run.sh to point to your apollocaffe installation?

**Comment by jwyang** [comment]
Yes, I have configured, and the path is correct. 

I just found in the apollocaffe/build/install/python folder, I could not found a folder named apollocaffe. Does it means that I have not yet compiled apollocaffe? Since in folder apollocaffe/python, I found two subfolders: caffe and apollocaffe. Should I modify the CMakeLists.txt in this folder and reinstall?

**Comment by jacobandreas** [comment]
Do you have the file `./python/apollocaffe/cpp/_apollocaffe.so`? Otherwise
you have not successfully built apollocaffe.

**Comment by jwyang** [comment]
no, i cannot find the file. Maybe I have not built it, I will check why that happened. thanks
