### ISSUE TITLE
VQA Images

### ISSUE THREAD

**Issue by omidb** [jacobandreas/nmn2#4]
Hi,

I am trying to set up your tool for VQA. Is it possible to point to pre computed images in specific format you mentioned in README?

Thanks

**Comment by jacobandreas** [comment]
The precomputed representations are huge and not easy to distribute. But they're easy to make on your own. Here's a [gist](https://gist.github.com/jacobandreas/897987ac03f8d4b9ea4b9e44affa00e7) with the script I use for doing the precomputation locally. You'll have to change a few paths at the top of the file to reflect the configuration of your system.

**Comment by nishithbsk** [comment]
In line 64 of the gist `embeddings = net.blobs["pool5"].data.copy()`, using pool5 gives a 512x7x7 output, not 512x14x14 as mentioned in the README. Could you please clarify? Thanks!

**Comment by jacobandreas** [comment]
Hi,

Sorry about the really slow reply. You can resize the input images by a
factor of 2 before preprocessing to get 14x14 outputs. (Both Caffe and
scipy have utilities for doing this in code.) You can also just use the 7x7
images---IIRC there's not much of a difference.
