### ISSUE TITLE
How to generate Questions/{train2014,val2014,...}.sps2

### ISSUE THREAD

**Issue by gujiuxiang** [jacobandreas/nmn2#5]
Hi, how to generate the following files: Questions/{train2014,val2014,...}.sps2

**Comment by jacobandreas** [comment]
If you just want to run the experiments:

> For VQA, these files should be named Questions/{train2014,val2014,...}.sps2. For GeoQA, they should be named environments/{fl,ga,...}/training.sps. Parses used in our papers are provided in extra and should be installed in the appropriate location.

(from the README).

I haven't gotten around to cleaning up the code used to generate these, but the basic procedure is outlined in the paper.
