### ISSUE TITLE
Training.sps file missing from the data set

### ISSUE THREAD

**Issue by suraj-vantigodi** [jacobandreas/nmn2#6]
Training.sps file missing from the data set, while running the example code for the geographical questions. Below is the error message I get.

`"IOError: [Errno 2] No such file or directory: 'data/geo/environments/fl/training.sps"`

Can you tell me how to generate the file and what does it contain?

**Comment by jacobandreas** [comment]
From the README:

> For VQA, these files should be named `Questions/{train2014,val2014,...}.sps2.` For GeoQA, they should be named `environments/{fl,ga,...}/training.sps.` Parses used in our papers are provided in `extra` and should be installed in the appropriate location.
