### ISSUE TITLE
How to generate attention maps?

### ISSUE THREAD

**Issue by nishithbsk** [jacobandreas/nmn2#9]
Hi,

I was hoping to obtain the attention maps generated by the Find Module. Currently, I'm extracting one of the sigmoid blobs from the apollo net using `att_data=model.apollo_net.blobs['Find_3_sigmoid'].data[i_datum,...]` after the forward pass. 

1) Would this be the right way to get attention? I'm skeptical since the maps I've obtained do not seem correspond with the image/question.
2) If it is the right way, how do I choose what "Find_%d_sigmoid" to use?

Thanks a lot!

**Comment by jacobandreas** [comment]
Hi Nishith,

Sorry about the extremely slow reply. What you're doing looks right. I've
noticed that the attention maps tend to get worse over time as the model
overfits. The default config will run for 30 iterations, but you usually
want to cut it off at closer to 20. You can look at the `Nmn` class
definition in nmn.py to see how indices get assigned to modules. Finally,
there's some existing visualization code in main.py that will automatically
save attention maps into the vis directory, so you can monitor them as
training proceeds.

Hope that helps!
